number1 = int(input("enter the value : "))
number2 = int (input("enter the value : "))
Addition = int(number1) + int(number2)
print ("Addition:",Addition)
Subtraction = int(number1) - int(number2)
print ("Subtraction:",Subtraction)
Multiplication = int(number1) * int(number2)
print("Multiplication:",Multiplication)
Division = float(number1) / float(number2)
print("Division:",Division)